SELECT 'Patient Count:' AS Label, COUNT(*) FROM PATIENT
UNION ALL
SELECT 'Admission Count:', COUNT(*) FROM ADMISSION
UNION ALL
SELECT 'Allergy Count:', COUNT(*) FROM PATIENT_ALLERGY;

SELECT * FROM PATIENT LIMIT 10;
SELECT * FROM ADMISSION LIMIT 10;
SELECT * FROM PATIENT_ALLERGY LIMIT 10;