DROP TABLE IF EXISTS ADMISSION;
DROP TABLE IF EXISTS PATIENT_ALLERGY;
DROP TABLE IF EXISTS PATIENT_INSURANCE;
DROP TABLE IF EXISTS EMERGENCY_CONTACT;
DROP TABLE IF EXISTS PATIENT_MEDICAL_HISTORY;

DROP TABLE IF EXISTS PATIENT;